name: flutter_blue_plus
description: Flutter plugin for connecting and communicationg with Bluetooth Low Energy devices, on Android and iOS
version: 1.1.1
homepage: https://github.com/boskokg/flutter_blue_plus

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  convert: ^3.0.0
  protobuf: ^2.0.0
  rxdart: ^0.27.0
  collection: ^1.15.0
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.boskokg.flutter_blue_plus
        pluginClass: FlutterBluePlusPlugin
      ios:
        pluginClass: FlutterBluePlusPlugin