name: flutter_blue_plus
description: Flutter plugin for connecting and communicating with Bluetooth Low Energy devices.
version: 2.0.6
homepage: https://github.com/tnc1997/flutter-blue-plus

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus_android:
    git:
      url: https://github.com/tnc1997/flutter-blue-plus.git
      path: packages/flutter_blue_plus_android
      ref: flutter_blue_plus_android-v2.0.5
  flutter_blue_plus_ios:
    git:
      url: https://github.com/tnc1997/flutter-blue-plus.git
      path: packages/flutter_blue_plus_ios
      ref: flutter_blue_plus_ios-v2.0.3
  flutter_blue_plus_linux:
    git:
      url: https://github.com/tnc1997/flutter-blue-plus.git
      path: packages/flutter_blue_plus_linux
      ref: flutter_blue_plus_linux-v2.0.1
  flutter_blue_plus_macos:
    git:
      url: https://github.com/tnc1997/flutter-blue-plus.git
      path: packages/flutter_blue_plus_macos
      ref: flutter_blue_plus_macos-v2.0.4
  flutter_blue_plus_platform_interface:
    git:
      url: https://github.com/tnc1997/flutter-blue-plus.git
      path: packages/flutter_blue_plus_platform_interface
      ref: flutter_blue_plus_platform_interface-v2.0.1
  flutter_blue_plus_web:
    git:
      url: https://github.com/tnc1997/flutter-blue-plus.git
      path: packages/flutter_blue_plus_web
      ref: flutter_blue_plus_web-v2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_blue_plus_android
      ios:
        default_package: flutter_blue_plus_ios
      linux:
        default_package: flutter_blue_plus_linux
      macos:
        default_package: flutter_blue_plus_macos
      web:
        default_package: flutter_blue_plus_web
