name: flutter_blue_plus_example
description: Demonstrates how to use the flutter_blue_plus plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  flutter_blue_plus:
    # Note: We use a path dependency because the example app & plugin are bundled together.
    # In *your* app you should use ^1.17.3 or similar
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0

dependency_overrides:
  # Note: We use these dependency overrides to test the example app with the latest changes.
  # In *your* app you should not add these overrides
  flutter_blue_plus_android:
    path: ../../flutter_blue_plus_android
  flutter_blue_plus_darwin:
    path: ../../flutter_blue_plus_darwin
  flutter_blue_plus_linux:
    path: ../../flutter_blue_plus_linux
  flutter_blue_plus_platform_interface:
    path: ../../flutter_blue_plus_platform_interface
  flutter_blue_plus_web:
    path: ../../flutter_blue_plus_web

flutter:
  uses-material-design: true

  # see https://docs.flutter.dev/packages-and-plugins/swift-package-manager/for-app-developers
  # disable-swift-package-manager: true
