name: flutter_blue_plus_example
description: Demonstrates how to use the flutter_blue_plus plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.33.0

# Note: We use path dependency overrides because the example app & plugin are bundled together.
# In *your* app you should omit this dependency overrides section.
dependency_overrides:
  flutter_blue_plus:
    path: ../
  flutter_blue_plus_android:
    path: ../../flutter_blue_plus_android
  flutter_blue_plus_darwin:
    path: ../../flutter_blue_plus_darwin
  flutter_blue_plus_platform_interface:
    path: ../../flutter_blue_plus_platform_interface

flutter:
  uses-material-design: true
