name: flutter_blue_plus_android
description: Android implementation of the flutter_blue_plus plugin.
version: 4.0.5
homepage: https://github.com/chipweinberger/flutter_blue_plus

environment:
  sdk: ^3.0.0
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus_platform_interface: ^4.0.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: flutter_blue_plus
    platforms:
      android:
        package: com.lib.flutter_blue_plus
        pluginClass: FlutterBluePlusPlugin
        dartPluginClass: FlutterBluePlusAndroid
