name: flutter_blue_plus_web
description: Web implementation of the flutter_blue_plus plugin.
version: 3.0.1
homepage: https://github.com/chipweinberger/flutter_blue_plus

environment:
  sdk: ^3.3.0
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus_platform_interface: '>=3.0.0 <5.0.0'
  flutter_web_plugins:
    sdk: flutter
  web: '>=0.5.0 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    implements: flutter_blue_plus
    platforms:
      web:
        pluginClass: FlutterBluePlusWeb
        fileName: flutter_blue_plus_web.dart
